### ISSUE TITLE
Symmetric NAT

### ISSUE THREAD

**Issue by r3a1d3a1** [suutaku/sshx#8]
Does this work if the SSH server is behind a symmetric NAT (i.e. NAT [behavior](https://datatracker.ietf.org/doc/html/rfc4787#section-4) & [filtering](https://datatracker.ietf.org/doc/html/rfc4787#section-5) are address & port dependant) ?

**Comment by suutaku** [comment]
it should works.

**Comment by suutaku** [comment]
> Thanks. I will have to try; but, based on [this](https://stackoverflow.com/a/65097630/205741), such a scenario would need a TURN (relay) server.

yes, maybe you don't need relay. try some public STUN sever like [google's](https://gist.github.com/sagivo/3a4b2f2c7ac6e1b5267c2f1f59ac6c6b).  let's see if WebRTC works.
